<!--
  FILE : hilo-2.asp
  PROJECT : assignment-WDD-A04
  PROGRAMMER : Yinruo Jiang
  FIRST VERSION : 2021-10-12
  SECOND VERSION : 2021-10-13
  DESCRIPTION : This source demonstrates the Hi-Lo game, which allow the user guess the number generated by program
-->
<!DOCTYPE html>
<html>
  <head>
    <title>Hi-Lo Game</title>
    <link rel="stylesheet" type="text/css" href="theHiLo/hilostyles.css">
  </head>
  <script type="text/javascript">
    //FUNCTION : function checkGuessNum()
    //DESCRIPTION : This function validate the user input of guessing number
    //PARAMETERS : guessNum as integer
    function checkGuessNum(guessNum) 
    {
      error.innerHTML = "";

      if ((guessNum.trim()).length == 0)
      {
        error.innerHTML = "Your guess number <b>cannot</b> be BLANK.";
      } 
      else 
      {
        if (isNaN(guessNum.trim()) == true) 
        {
            error.innerHTML = "You <b>must</b> enter an integer which can not contain letter or space";
        }
        else if (Number.isInteger(Number(guessNum.trim())) == false)
        {
          error.innerHTML = "You <b>must</b> enter an integer not a float or double";
        }
        else 
        {
            numValid = true;
            error.innerHTML = "";
            document.GuessNumForm.submit();  
        }
      }
    }

    //FUNCTION : function invalidResult(minNum,maxNum,guessNum)
    //DESCRIPTION : This function validate the user input of guessing number whether it is larger than zero and minNum and smaller than //              maxNum
    //PARAMETERS : minNum as integer 
    //             maxNum as integer
    //             guessNum as integer
    <%
    sub invalidResult(minNum,maxNum,guessNum)
      If(initStage <> True) Then
        //If guessing number smaller than zero, set error message
        If(guessNum <= 0) Then
          Response.Write("You <b>must</b> enter an integer greater than zero.")
        ElseIf  (guessNum > maxNum or guessNum < minNum ) Then 
          //If guessing number smaller than minNum or larger than maxNum, set error message
          Response.Write("Sorry you are out of range.")
        End If
      End If
    end sub
    %>

    //FUNCTION : function validResult(minNum,maxNum,numToGuess,guessNum)
    //DESCRIPTION : This function validate the user input of guessing number whether matches with the numToGuess and update the guessing //              range
    //PARAMETERS : minNum as integer 
    //             maxNum as integer
    //             numToGuess as integer
    //             guessNum as integer
    <%
    sub validResult(minNum,maxNum,numToGuess,guessNum)
      //If guessing number smaller than the numToGuess, update the guessing range
      If(guessNum < numToGuess) Then
        If (guessNum >= minNum) Then
          minNum = guessNum + 1
        End If
        Response.Write("Your allowable guessing range is any value between " & minNum & " and " & maxNum)
      ElseIf  (guessNum > numToGuess) Then
        //If guessing number smaller than the numToGuess, update the guessing range
        If (guessNum <= maxNum) Then
          maxNum = guessNum -1      
        End If
        Response.Write("Your allowable guessing range is any value between " & minNum & " and " & maxNum)
      ElseIf (guessNum = numToGuess) Then
        //If user get the right number, redirect to next page
        Response.Redirect "hilo-3.asp"
      End If
    end sub
    %>
  </script>
  <body>
    <%
      Public maxNum
      Public minNum 

      dim fname
      dim guessNum
      dim numToGuess
      Public initStage
      
      fname=Request.Cookies("fname")
      initStage = True

      numToGuess = CInt(Request.Cookies("numToGuess"))

      If Request.Form("guessNum") <> "" Then
        initStage = False
      End If

      If IsNumeric(Request.Form("guessNum")) Then
        guessNum = CInt(Request.Form("guessNum"))
      End If

      maxNum = Request.Form("maxNum")
      If(maxNum <> "") Then
        maxNum = CInt(maxNum)
      Else
        <!-- maxNum cookie is set in the previous page -->
        maxNum = CInt(Request.Cookies("maxNum"))
      End If

      minNum = Request.Form("minNum")
      If(minNum <> "") Then
        minNum = CInt(minNum)
      Else
        minNum = CInt(1)
      End If

    %>

    <form action="hilo-2.asp" method="post" name="GuessNumForm">
      <p>
        <%=fname%> - We are playing Hi-Lo!
        <br><br>
        Enter your guess <input type="text" name="guessNum" value="" size="20" autofocus/>
        <input type="button" value="Make this Guess" onclick="checkGuessNum(guessNum.value);" />
      </p>
      <div id="error" style="color:red;">
        <%call invalidResult(minNum,maxNum,guessNum)%>
      </div>
      <div id="hint" style="color:whitesmoke;">
        <%call validResult(minNum,maxNum,numToGuess,guessNum)%> 
      </div>

      <input type="hidden" name="maxNum" value="<%=maxNum%>" />
      <input type="hidden" name="minNum" value="<%=minNum%>" />
    </form>
  </body>
</html>